language: objective-c
script:
  - xctool -project TryJSON.xcodeproj -scheme TryJSON -sdk iphonesimulator
  - xctool -project TryJSON.xcodeproj test -scheme TryJSON -sdk iphonesimulator
before_install:
  - brew update
  - brew uninstall xctool && brew install --HEAD xctool
matrix:
  include:
    - osx_image: xcode7.2
    - osx_image: xcode7.3
